### PR TITLE
Change copyright from Filament Group to Scott Jehl

### PR DESCRIPTION
**Pull request by pra85**

### CODE REVIEW

**Comment by mike-engel** [comment]
@pra85 Is there a reason for this change? As far as I know, this is still Copyrighted by Filament Group.

**Comment by mike-engel** [comment]
Maybe @wilto or @scottjehl can weigh in.

**Comment by mike-engel** [comment]
@pra85 I'm going to go ahead and close this PR. Filament Group is still the copyright holder with this package (even though it's under Scott's github name).

**Comment by scottjehl** [comment]
:+1: thanks tho

**Comment by pra85** [comment]
No problems, thanks for clarifying :+1:

**Pull request closed without merging**
