### PR TITLE
Fix #464 - Added support for logical operators in media queries

### LINKED ISSUE #266: 2x image size behaviour does not match native Chrome
``
With the above markup and no size attributes or CSS sizing, non-Chrome browsers display the 2x image at the original size, so that it appears twice as big when on a 2x display.

In Chrome however the 2x image is displayed at half size, so that it appears to be the same size as the 1x image.

The same issue occurs with any of these too:
``
``
``

Also, with this markup a 1x display connected to a 2x device (external monitor on a Retina MacBook Pro) will load the 2x image:
``

Chrome continues to work fine in that situation though.

I'm in a situation where I cannot apply a size with HTML or CSS to constrain the 2x image to the original size, so that's out of the question. I could use max-width/height for some constraint, but if the 1x image is smaller than that size then the 2x version will still look bigger.

### LINKED ISSUE #464: Add support for logical operators in media queries passed in sizes strings
As I have explained the issue here:
https://github.com/ResponsiveImagesCG/picture-element/issues/266

### PR DESCRIPTION
**Pull request by przemyslaw-piatek**
Changed regex to capture multiple queries connected with "and" or "or" logical operators.

* Automated tests passed
* Handmade tests passed
* Candidate regex performance checked: http://jsperf.com/picturefill-regex-candidate

### CODE REVIEW

**Comment by Pshem** [comment]
Sorry for using bad issue id in both branch name & commit message, my bad.
Changed the issue title to reflect the correct issue id: https://github.com/scottjehl/picturefill/issues/464

Please let me know if you need the branch to be renamed - I'll send another pull request.

**Comment by aFarkas** [comment]
I haven't tested the code, but it is a great addition. Just some questions:

###Adding **not**
Beside from current browser support. From looking into [MQ4](http://drafts.csswg.org/mediaqueries/#media-conditions): 

> Multiple media features can be combined together into a media condition
using full boolean algebra (not, and, or).

So we can/should also add *not* to the combinator list?

###Multiple combination
As I said, I haven't tested it, but it looks like this code only allows to combine two media conditions. I think we should support more.

**Comment by aFarkas** [comment]
I just double checked. In [this branch](https://github.com/scottjehl/picturefill/tree/afarkas-pf3-proposal) there is full support for what you want. And it already supports unlimited combinations of media conditions even with the not operator.

**Comment by Pshem** [comment]
What you have linked looks good, but - in my humble opinion - overcomplicated in most cases.

I do realize that increasing complexity of a string may have serious performance consequences when using regex approach, but I gave it a try whatsoever.

I have pushed another commit with extended support you asked for, plus here are two performance tests showing that regex approach in complex scenarios are around 10-15% slower in general:
* http://jsperf.com/picturefill-regex-candidate-performance-simple
* http://jsperf.com/picturefill-regex-candidate/11

You can now properly catch media queries such as:
```
only screen and (((min-width: 30em) and (max-width: 50em)) or (min-width: 150em)) calc(30% - 15px), 
(min-width: 30em) calc(30% - 15px), 
(min-width: 40em) and (max-width: 50em) 20%, 
(min-width: 50.01em) and all 30%, 
(min-width: 80em) 40%, 
not print 50%, 
60%
```

If one can afford such performance drop, I believe that what I proposed should be a good compromise between keeping the codebase small&simple and precise specs implementation.

I won't be sticking to my guns if you find it too much of a shortcut, though ;)

**Comment by aFarkas** [comment]
@przemyslaw-piatek 
Actually I haven't asked for multiple nested parenthesis parsing. I think we only should add the *not* operator.

Something like this:

``/((?:\([^)]+\)(?:\s*and\s*|\s*or\s*|\s*not\s*)?)+)?\s*(.+)/g``

Also note: That in sizes only media conditions not media queries are supported. This means ``"only screen"`` or ``"print"`` are invalid. As also ``%`` CSS units.

What we should support:

``(min-width: 30em) and (max-width: 50em) or (min-width: 150em) not (min-resolution: 144dpi)``

About the code in the branch, it is pretty small, if minified and gzipped and a quite strict implemenation of the sizes parser, in the long run we clearly want to use this one.

I don't think, that a perf cost of 10-20% is a problem for picturefill. The sizes parsing doesn't take long compared to the other tasks we are running. Additionally we can add some memoization, because in a real world enviroment the sizes strings  for many different images will often be repeated in the document.

**Comment by aFarkas** [comment]
@przemyslaw-piatek 
Would you just add the ``not`` operator and request a PR against our 2.4 branch? I really like this enhancement.

**Comment by przemyslaw-piatek** [comment]
Of course, it just has to wait until tomorrow ;)

**Pull request closed without merging**
