### PR TITLE
rewrite tests to use intern

### LINKED ISSUE #489: Test strict mode, nightly browsers
#478 could have been discovered earlier if we were testing picturefill with WebKit trunk (which supports `currentSrc` but not `HTMLPictureElement`; shipped Safari does not support `currentSrc`) and `"use strict"`. Evidently this was not done, but sites are using picturefill in strict mode.

* Run the tests both with and without `"use strict"`.
* Run the tests in nightly browsers as well to catch problems early.

(Possibly also quirks mode/standards mode and IE's dozens of compat modes, if you will.)

### PR DESCRIPTION
**Pull request by patrickkettner**
fixes #489...sorta

I changed the testing to use intern's QUnit's interface. It will still need to have a browserstack API (tested locally with mine, and it works).

For this to be actually useful, something akin to https://github.com/twbs/savage would need to be added for PRs. In addition, for the actual ask of #489 to be fulfilled, some kind of box that auto downloads the latest versions of browsers and runs this against them. Travis wouldn't work well for this, since its essentially linux only (there _is_ os x support, but its invite only and really only meant for iphone apps). AppVeyor could work, since it runs on windows, but it would be an fairly non standard env. So a mac mini or custom windows hosting somewhere where chrome canary, firefox nightly, webkit nightly, and edge could be installed would probably be best (imo, at least).

### CODE REVIEW

**Comment by mike-engel** [comment]
@patrickkettner This PR is against `master`, which equates to 2.3.1. Just want to make sure this is correct and you didn't mean to do it against our `3.0` branch.

**Comment by patrickkettner** [comment]
I can point it against whatever y'all would like

**Comment by patrickkettner** [comment]
it applies cleanly to the 3.0 branch, so lemme know and I can update one way or the other

**Comment by mike-engel** [comment]
@patrickkettner Ok cool, let's do it against 3.0 and keep it up to date with that moving forward.

Additionally, it looks like a bunch of JSCS tests failed (see travis). Mind fixing those quick?

**Comment by patrickkettner** [comment]
sure - multiline strings are disallowed, as are lines that are over 100 chars. What should I do about the more verbose test descriptions that were ported over?

**Comment by patrickkettner** [comment]
updated

**Comment by patrickkettner** [comment]
closing to retarget the PR

**Pull request closed without merging**
