### PR TITLE
extend sizes feature detect for Safari 9

### PR DESCRIPTION
**Pull request by aFarkas**
This is clearly not ready for merge yet. I need to do some more testing, but want to have some early eyes on the changes.

### CODE REVIEW

**Comment by aFarkas** [comment]
@yoavweiss fixed this bug. In case this is coming into Safari 9.0.1/9.0.2 we might not need these changes.

For more information:
https://bugs.webkit.org/show_bug.cgi?id=150230

**Comment by aFarkas** [comment]
This PR is now ready for review. If I can do something to speed up the process, please let me know.

**Comment by mike-engel** [comment]
Looks ok to me, and if tests pass, +1

**Comment by aFarkas** [comment]
Happy! Thanks.

**Pull request merged**
