### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by mike-engel** [comment]
@kkirsche This does say, however, that it may be used in the future. Is there a good reason to leave it in until bower actually has a registry?

**Comment by kkirsche** [comment]
@mike-engel my understanding from the discussions I've had is that Bower is even recommending that people use NPM. It was originally added for the sake of someone building a package manager. This never happened and people went around NPM. It's a slow death for bower but there isn't a good reason to keep this as I understand it.

**Comment by mike-engel** [comment]
Alright, +1 I guess. It doesn't _hurt_ to take it out, and it's one less thing to change when we publish.

**Comment by mike-engel** [comment]
Should go into 3.0 though, not 2.3.

**Comment by aFarkas** [comment]
+1 (sry for the silence

**Comment by mike-engel** [comment]
Done with 432081d. Goes into 3.0. Thanks @kkirsche

**Pull request closed without merging**
