### PR TITLE
Minor typo fix :)

### PR DESCRIPTION
**Pull request by greystate**
Not sure if I need to create an issue and not PR against `master`, but here goes... :pray:

### CODE REVIEW

**Comment by jegtnes** [comment]
Good spot. Thank you very much for this, @greystate!

I'm not 100% sure what our branching strategy is at the moment. @mike-engel / @aFarkas, can you remind me—are we meant to PR against version branches and then merge into master?

**Comment by mike-engel** [comment]
Technically this should be against the `3.0` branch, but we can manually merge it into 3.0 with the command line. I'm tempted to alter the branching strategy a bit, but that's for another place :smiley:. For now, it's not worth it to open another PR.

:+1:

**Comment by aFarkas** [comment]
+1

**Comment by jegtnes** [comment]
You can do PRs for any branch into any branch, so I just created one for getting 3.0 up to date with master. Check out #612

**Pull request merged**
