### PR TITLE
summarize 3.0 alpha features

### PR DESCRIPTION
**Pull request by baloneysandwiches**
and banish all mention of 2.2.0 from everything going forward...

### CODE REVIEW

**Comment by mike-engel** [comment]
+1

**Comment by aFarkas** [comment]
> the default download packages include the <a href="https://github.com/paulirish/matchMedia.js/">matchMedia polyfill</a> for browsers that need it (like IE9)

We actually do not include this anymore. Due to the fact, that we have a simple shim, that also supports IE8, we use this for IE9 too. The simple shim, polyfills min-width/max-width/min-height/max-height (comma separated or combined with and). If more complex media queries in combination with IE9 needs to be supported the matchMedia polyfill can be included (for example orientation/min-/max- aspect-ratio).

**Comment by baloneysandwiches** [comment]
@aFarkas Thanks, please look again.

**Comment by aFarkas** [comment]
+1

**Comment by aFarkas** [comment]
thx!

**Pull request merged**
