### PR TITLE
fixes scottjehl/picturefill#432

### PR DESCRIPTION
**Pull request by saranrapjs**
This very simply checks for a `parent` when looking for parent `picture` elements, which accounts for situations where an img that needs srcset is parentless.

### CODE REVIEW

**Comment by mike-engel** [comment]
Seems ok to me but I'll let some core members chime in. While we wait, is there a reason you would be running picturefill on an element before its in the DOM? Simply to have it ready before inserting?

**Comment by saranrapjs** [comment]
Yup — so that I can preload the image that `srcset` determines to be the best fit.  Particularly useful in cases where you're switching from a data-uri image (without `srcset`) to a "real" image (with `srcset`), and I want the swap to appear seamless.

**Comment by aFarkas** [comment]
+1. I used similar patterns to load an image in the background and then transferring the ``currentSrc`` as a background image or for preloading prev/next images in a gallery/lightbox.

While not direct part of our jcs, I would add some extra whitespace after the opening and before the closing parenthesis. (This is typical for pf code).

A small test would also be great.

```js
var img = document.createElement( "img" );
img.setAttribute( "srcset", "data:img 500w" );
picturefill( { elements: [ img ] } );
assert.equal( img.currentSrc || img.src, "data:img" );
```

**Comment by saranrapjs** [comment]
OK — changed the whitespace to match the spec, and added that test case verbatim.

**Comment by aFarkas** [comment]
thx

**Comment by Wilto** [comment]
+1

**Pull request merged**
