### PR TITLE
Add package.json for npm compatibility

### PR DESCRIPTION
**Pull request by malinow**
Hi!
Just added a "barebones" package.json for 1.2.1 on the 1.2 branch so I can consume this with npm for our projects.
Thanks for your hard work!
MM

### CODE REVIEW

**Comment by quoo** [comment]
You specifically need this for 1.2? Version 2 is the latest and has a package.json set up already.

**Comment by malinow** [comment]
Hi @quoo-
Yep, we need the old `<span>` way of doing things that 1.2 has. We're just consuming our own fork right now but I figured I'd push it up here to save other people the effort of forking just for this.
Thanks!
MM

**Comment by mike-engel** [comment]
+1, but paging @wilto to be super-certain.

**Comment by Wilto** [comment]
Yeah; this makes sense. How do we handle that, exactly? Publish it as like `picturefill-old` or something?

**Comment by mike-engel** [comment]
@Wilto we would just publish to npm from the 1.2 branch, which with this package.json, would publish as 1.2.0. People could then run `npm install picturefill@1.2.0` to get this specific version. People running `npm install picturefill` would still get 2.3.0.

**Comment by Wilto** [comment]
Ah-hah. Sold.

**Comment by mike-engel** [comment]
Alright @wilto, changes are up in the `1.2` branch. All you should need to do now is an `npm publish` from that branch.

**Pull request merged**
