### PR TITLE
Add WebP `type` support back into core.

### PR DESCRIPTION
**Pull request by Wilto**
Kiiinda want to leave this in here, so users can unhook the types extension without any unexpected behavior. It does mean some redundant code though, and changes like this aren’t _entirely_ unforgivable since we’re moving from PF2 -> PF3 anyway. What do we think?

### CODE REVIEW

**Comment by mike-engel** [comment]
@wilto, looks like jshint tests are failing. Wanna take a look?

**Comment by aFarkas** [comment]
Yeah, basically this is a cleaned up version for pf2. The ``w`` namespace is ``window`` in pf3 and the ``pf`` namespace is ``ri``. I think it is my turn to fix the later one. I was just too lazy.

**Comment by aFarkas** [comment]
Don't really understand the rationale about this change (re-add). 
My guess: Developers targeting users with webP, but without picture support, shouldn't be forced to use the additional plugin. Am I right?

**Comment by Wilto** [comment]
Oh good; nice. I ran grunt on the wrong branch. _Nailing it_.

Yeah; the idea is that Picturefill core currently does WebP and SVG without the extension—devs switching over to PF3 might expect the same.

**Comment by aFarkas** [comment]
+1

**Pull request merged**
