### PR TITLE
Pr 3.0.2

### PR DESCRIPTION
**Pull request by aFarkas**

### CODE REVIEW

**Comment by mike-engel** [comment]
Should this go into the 3.0 branch?

**Comment by aFarkas** [comment]
@mike-engel 
Yes, here is the [PR for this](https://github.com/scottjehl/picturefill/pull/598). As I understood our branching.

But I'm not totally on top of our branching strategy. What I think we have:

* Bug fixes releases go in to their corresponding major branch (i.e.: 3.0.2 goes into 2.0).
* latest stable release goes into master (i.e.: 3.0.2 -> master)
* releases that should be visible to public go in to gh-pages (i.e: 3.0.2 -> gh-pages)

We could also just do the PR for 3.0 and then merge from there into the other branches. This is what you expected, right?

**Comment by mike-engel** [comment]
So, the way I've been seeing it, @aFarkas, is that all work on a version goes into that version branch. When we're ready to publish a new version, then we push it to master. I'll try and make a diagram later tonight or this week.

**Comment by aFarkas** [comment]
As I described what I did, it came to me that this is not best. Stupid me.

**Pull request closed without merging**
