### PR TITLE
Smarter resource selection

### PR DESCRIPTION
**Pull request by aFarkas**

### CODE REVIEW

**Comment by Wilto** [comment]
Checking in with @yoavweiss on this one; I don’t want to deviate from native anywhere in here.

**Comment by yoavweiss** [comment]
I'd prefer to leave such "preference" features to extensions. Browsers are not throttling on 2x, and are not planning to AFAIK.

**Comment by yoavweiss** [comment]
by extensions I mean a "picturefill plugin", not a browser extension

**Comment by aFarkas** [comment]
@yoavweiss 
There is [already one](http://afarkas.github.io/lazysizes/optimumx/).

But I thought you would make somewhere the cut. [Your comment](https://github.com/scottjehl/picturefill/issues/325#issuecomment-55539783) sounded so.

But I will remove this asap

**Comment by yoavweiss** [comment]
Thanks! :) I'm certainly interested in hearing about experimentations like that, but have no immediate plans to bring that into the native implementation. Sorry if my comment wasn't clear enough in that regard.

**Comment by aFarkas** [comment]
Well, I have no 3x device, but I think this is something, that should be tested with a variety of images (perceived perf vs. perceived quality), but I guess the quality improvements aren't that good satisfying so much data transfer.

**Comment by Wilto** [comment]
Reviewed; +1.

**Comment by mike-engel** [comment]
@aFarkas Looks like the original branch for this has been deleted. We still looking to get this in or can we close this one out?

**Comment by aFarkas** [comment]
I think this is dead. Would still have feedback for the meta issue here: https://github.com/scottjehl/picturefill/issues/497

**Pull request closed without merging**
