### PR TITLE
Ios scrollbug 544

### PR DESCRIPTION
**Pull request by aFarkas**
This fixes issue #544. See there for more informations.

### CODE REVIEW

**Comment by mike-engel** [comment]
@aFarkas Looking at the diff, does this just basically force PF to re-evaluate every 99ms?

**Comment by aFarkas** [comment]
The [debounce line](https://github.com/scottjehl/picturefill/commit/a58deb6852c460297528ed7e01922ecf729d35be#diff-e3cc12fee32d40e95863f7b6bee3e282R1384) means, that picturefill is re-evaluated 99ms after the last resize event. So if the user is resizing and multiple resize events are fired, only one re-evaluation is done with a delay of 99ms.

**Comment by mike-engel** [comment]
Right, so with these changes though, we for pf to re-evaluate instead of running any checks, correct?

**Comment by aFarkas** [comment]
Don't really understand what you mean. 

If you look into the resulting diff: https://github.com/scottjehl/picturefill/pull/558/files#diff-bbe09cc8bdf0b3324bec848fd0f2641bR1443

The old way:
If a resize event is fired we run a debounced picturefill function.

The new way:
If a resize event is fired we run a debounced function, that checks whether width or height of viewport has changed (without checking innerHeight, because this is changed on scroll on iOS), if it has changed we run picturefill.

**Comment by mike-engel** [comment]
Oh dear, I was looking at the diff wrong. :disappointed: 

+1.

**Comment by verlok** [comment]
Hi! Was it already merged into 3.0 or still pending?

**Comment by aFarkas** [comment]
Not merged yet. Will do asap.

**Comment by verlok** [comment]
Thank you.

**Comment by aFarkas** [comment]
It's merged now.

**Pull request merged**
