### PR TITLE
resource selection cleanup (fixes #497)

### LINKED ISSUE #497: Cleanup source selection for pf 3.0 alpha
Before we can release pf 3.0-alpha-2, we need to do some cleanup tasks. One thing is the source selection.

I would like to implement a [similar algorithm like this one](http://jsfiddle.net/trixta/9dponzs2/). Or at least something that produces similar results.

As we know using always a mean, can result in bad results especially on low resolution displays. This is also the reason why Chrome dropped the mean approach for devices <= 1x.

I would like to take the chance to not follow Chrome's implementation and experiment by using a different approach.

The algorithm above uses a modified arithmetic mean approach. The modification is mainly based on the density of the lower resolution candidate (as an absolute indicator of image quality) and only slightly on the target resolution of the device. 

I think this best describes, what we see. If the resolution of the lower res image is already "high", it makes sense to go for less data and take this candidate. If the resolution is low it might be better to take the higher candidate.

### PR DESCRIPTION
**Pull request by aFarkas**

### CODE REVIEW

**Comment by aFarkas** [comment]
It would be nice, if someone could help me here with the documentation.

**Configuration-API:**

The configuration can be done before or after adding picturefill:

```js
//generating the config array
window.picturefillCFG = window.picturefillCFG || [];

//actual configuration
picturefillCFG.push([ "algorithm", "edge" ]);
```

The "edge" or "experimental" source selection algorithm behaves a little bit different from the default algorithm. The main differences compared to the default algorithm:

* on a 1x device, the "edge" algorithm will in rare cases take a lower resolution candidate (more performance/less quality)
* on a 1.5x device, the "edge" algorithm will sometimes choose a higher resolution candidate (less performance/more quality)
* on a 2x device, it will behave very similar to the default algorithm
* on 3x or higher resolution device it will often take lower resolution candidate (more performance/less quality)

**Comment by baloneysandwiches** [comment]
Just as far as the docs:
- Is there any possible duplication issue if authors set the config after loading PF at bottom of body? I know we're advising inserting the head, for simplicity. But scripts in the head kind of suck, even with async. It feels icky that we're recommending this. Can we advise:

    1) shiv in the head
    2) config at the bottom of the body, followed by the script?

 Got to find a balance here between ease of setup and best practices. Just want to be sure here we're covering all possible config scenarios.
- Do we need both "edge" and "experimental" option names if they're the same algo? Pick one? Or is this for compat? Once we're committed to both, we can never take one out :/

Also "More performance" might be the wrong phrase here. It's not code perf, it's data volume. Maybe something like "less data downloaded, less image quality". My two cents, otherwise LGTM.

**Comment by aFarkas** [comment]
> Is there any possible duplication issue if authors set the config after loading PF at bottom of body?

If the script is added at the bottom and the config is done after, you will get the result of the default algorithm. (Good question: Maybe we should recommend to configure before (always).)

> But scripts in the head kind of suck, even with async.

I don't think so. What do you mean? From perf it is important to put an async attribute there. If this was done, there is no perf improvement to move to bottom. Here is a nice quote from the master of move-your-scripts-to-bottom (http://www.stevesouders.com/blog/2015/05/12/hero-image-custom-metrics/):

> While moving scripts to the bottom was a good performance optimization in 2007, .... Today, for optimal performance it’s important to load scripts asynchronously.

> Do we need both "edge" and "experimental" option names
No, are there any preferences. 

Did you already looked into the code changes? Or is everything fine?

Thanks for your review!!! ;-)

**Comment by baloneysandwiches** [comment]
> Maybe we should recommend to configure before (always).

+1. Simpler, bulletproof.

> While moving scripts to the bottom was a good performance optimization in 2007, .... Today, for optimal performance it’s important to load scripts asynchronously.

Agreed. I'm talking about IE8 and 9 which don't support async. And once the author puts an `async` on the PF script tag, the author has no control over when it executes relative to any separate config code. We could advise adding any custom config code at the top of the PF file? Too complex?

>>    Do we need both "edge" and "experimental" option names

>No, do you have any preferences.

"Edge" is about to become a browser name :smiley_cat: so that seems potentially confusing as a config option name. "Experimental" sounds scary and break-ey. I would be concerned that no one would use it. Maybe something totally different like "clever" ? @wilto ?

**Comment by aFarkas** [comment]
Let's handle the concrete documentation in another task (will open an issue as soon as this is merged) and get only the option name right so it can be merged soon.

About the option name, I'm totally open to call it whatever. 

I even  think that 'experimental' isn't so bad, if the documentation gets it right in general. Because it is 'experimental', but tries to be "better" and in case people are using it and we also would like to have some feedback. (Especially if they experience concrete differences to the default implementation (basically Chrome).)

**Comment by mike-engel** [comment]
@baloneysandwiches If you're good with creating a new issue after this merge, do you want to merge this in?

**Comment by aFarkas** [comment]
@mike-engel 
I think we are not done yet here. What about 'alternate' as the option name?

**Comment by mike-engel** [comment]
Right. Sorry about that @aFarkas. As for the name, alternative sounds ok, but it's also bland. Will this "alternative" always have some consistent benefit over the default? Something like better performance, etc?

**Comment by aFarkas** [comment]
> Something like better performance
No, actually not. To put it very simple, it should have better performance on 3x/4x devices.

**Comment by mike-engel** [comment]
Alright. I guess it truly is an alternate, but we'll need to be very explicit in the docs about what it is, and what it does. @wilto @baloneysandwiches @aFarkas, what do we all think?

**Comment by baloneysandwiches** [comment]
My sense is that almost no one will actually ever use an option called "experimental" in production. The word is a pretty serious red flag. Maybe something like:

    "saveData" : Weights the resource selection algorithm towards smaller image candidates on
    very high dppx devices (3ddpx +), to conserve bandwidth.

**Comment by aFarkas** [comment]
+1 for ``"saveData"``.

**Comment by mike-engel** [comment]
+1 for `"saveData"` as well. 

make it so

**Comment by Wilto** [comment]
Works for me. I’d maybe chuck “uses a custom source selection algorithm unique to Picturefill” or something along those lines in the description, just to be explicit about the fact that this is a Picturefill deal.

**Pull request merged**
