### PR TITLE
💥 Update gh-pages branch to reflect latest changes in master

### PR DESCRIPTION
**Pull request by jegtnes**
We've got quite a few changes in master for `index.html` that never actually made it across to the gh-pages branch, which is where http://scottjehl.github.io/picturefill/ pulls the content from. Let's get them updated, shall we?

(Related to #474)

### CODE REVIEW

**Comment by aFarkas** [comment]
@jegtnes
This PR makes your fix version-number PR obsolet, right?

In this case I simply just want to merge this. +1....

What do you think, to simply delete our master branch and make gh-pages master?

**Comment by mike-engel** [comment]
@aFarkas I don't think we should get rid of the master branch. We should instead probably find a grunt task to mirror master onto gh-pages. Thoughts?

**Comment by aFarkas** [comment]
I'm not very opinionated here. Just thought that we mostly will only move things to master as soon as we do an official release and when we do, we should also always update gh-pages.

**Comment by Wilto** [comment]
+1 to automating things with a Grunt task.

**Pull request merged**
