### PR TITLE
Add Composer support

### PR DESCRIPTION
**Pull request by RobLoach**
This add support for the [Composer](https://getcomposer.org/) package manager for PHP.

### CODE REVIEW

**Comment by aFarkas** [comment]
Are you stalking me ;-)

**Comment by Wilto** [comment]
Another day, another package manager file.

+1, I guess.

**Comment by mike-engel** [comment]
Will need to be added to the publish grunt task for releases

**Comment by RobLoach** [comment]
> Will need to be added to the publish grunt task for releases

Composer actually handles releases for us through [the GitHub Packagist webhook](https://github.com/scottjehl/picturefill/settings/hooks). We just need to add Packagist in there, and releases are automagically added for us.

> Are you stalking me ;-)

Well hello there, @aFarkas :wink: .

**Comment by mike-engel** [comment]
> Composer actually handles releases for us through the GitHub Packagist webhook. We just need to add Packagist in there, and releases are automagically added for us.

Seems easy enough. +1.

**Pull request closed without merging**
